### ISSUE TITLE
Missing order "help build wonder"

### ISSUE THREAD

**Issue by lmoureaux** [Lexxie9952/fcw.org-server#15]
Units starting their turn on a city tile cannot help build wonder in the city without moving. This is possible with 'B' in the native clients.

**Comment by Lexxie9952** [comment]
The (D)o command allows this and other actions without overlapping other commands.

**Comment by lmoureaux** [comment]
Agreed but not very discoverable.

**Comment by DobbyK** [comment]
Should this be closed?
