### ISSUE TITLE
FCW C Server crash -  concat_tile_activity_text 

### ISSUE THREAD

**Issue by andreasrosdal** [Lexxie9952/fcw.org-server#164]
Stack trace from Freeciv C server crash:

Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/home/freeciv/freeciv/bin/freeciv-web --debug 1 --port 6055 --Announce none --e'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000555c7fc66e66 in concat_tile_activity_text ()
(gdb) bt full
#0  0x0000555c7fc66e66 in concat_tile_activity_text ()
No symbol table info available.
#1  0x0000555c7fb7f483 in popup_info_text ()
No symbol table info available.
#2  0x0000555c7fb88599 in handle_info_text_req ()
No symbol table info available.
#3  0x0000555c7fb7db05 in server_handle_packet ()
No symbol table info available.
#4  0x0000555c7fae50d2 in server_packet_input ()
No symbol table info available.
#5  0x0000555c7fbb6ba8 in server_sniff_all_input ()
No symbol table info available.
#6  0x0000555c7fae8405 in srv_main ()
No symbol table info available.
#7  0x0000555c7fadc99d in main ()
No symbol table info available.

**Comment by andreasrosdal** [comment]
@cazfi

**Comment by Lexxie9952** [comment]
Possibly/probably fixed by commit entitled "Probable fix to #164 + De-tangle multiple unit tile activities from UWT messaging logic + ..."
