### ISSUE TITLE
FCW C server crash - handle_unit_change_activity

### ISSUE THREAD

**Issue by andreasrosdal** [Lexxie9952/fcw.org-server#166]
Core was generated by `/home/freeciv/freeciv/bin/freeciv-web --debug 1 --port 6069 --Announce none --e'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005566acf9c8b0 in handle_unit_change_activity ()
[Current thread is 1 (Thread 0x7fee8319d800 (LWP 25026))]
(gdb) bt full
#0  0x00005566acf9c8b0 in handle_unit_change_activity ()
No symbol table info available.
#1  0x00005566acf51b78 in server_handle_packet ()
No symbol table info available.
#2  0x00005566aceb90d2 in server_packet_input ()
No symbol table info available.
#3  0x00005566acf8aba8 in server_sniff_all_input ()
No symbol table info available.
#4  0x00005566acebc405 in srv_main ()
No symbol table info available.
#5  0x00005566aceb099d in main ()
No symbol table info available.

**Comment by andreasrosdal** [comment]
@cazfi

**Comment by Lexxie9952** [comment]
Very likely fixed by commit entitled:
"Probable fix for issue #166"
