### ISSUE TITLE
Server connection seems to fail if username starts with a digit.

### ISSUE THREAD

**Issue by funkybob** [Lexxie9952/fcw.org-server#167]
I wanted to start a single player game, but for the last couple of days when I try it loads the foyer, but can't stay connected. If I try to set the config, the values are all empty. If I try to select a nation, nothing happens, and eventually I get a message saying the connection failed.

However, When I changed my name from '1Bob' to 'FBob', the problem went away.

**Comment by Lexxie9952** [comment]
Thank you for reporting. The first letter of a username must be an unaccented Latin alphabetic character. An error message to this effect will now be in the next rebuild.
