### ISSUE TITLE
More robust supercows.txt parsing

### ISSUE THREAD

**Issue by andreasrosdal** [Lexxie9952/fcw.org-server#27]
FIXME! This method needs to be reviewed to prevent segmentation faults if the supercows file contains invalid text.

https://github.com/Lexxie9952/fcw.org-server/commit/2ee0536fe1923e53161b846bde25a16d4ca36472#diff-ec02b538612aa7bf8f2c54f2561be2c6R3730

**Comment by JosiahWI** [comment]
What should the correct behavior be when the text is invalid? If the method returns false is that acceptable?

**Comment by andreasrosdal** [comment]
Yes, then it should return False. Most importantly, not segfault.

**Comment by andreasrosdal** [comment]
we also need help with this:
https://github.com/freeciv/freeciv-web/issues/319
