### ISSUE TITLE
Tech tree not shown in Brave (Debian GNU/Linux, amd64)

### ISSUE THREAD

**Issue by kvilhaugsvik** [Lexxie9952/fcw.org-server#43]
It is still possible to select a tech by hovering over the empty space and selecting the tech based on pop up help

**Comment by andreasrosdal** [comment]
Can you post a screenshot? Are there errors in the JavaScript console?

**Comment by kvilhaugsvik** [comment]
No errors in the JavaScrip console.

GitHub refuses to upload my screen shot.

Lexxie tested with Brave on Windows 10 and it worked there, even in private mode.

**Comment by kvilhaugsvik** [comment]
![Skjermbilete_2021-03-20_21-33-50](https://user-images.githubusercontent.com/6710184/112378190-ed81b700-8ce6-11eb-9273-314c646a60a1.png)

It was NoScript in my Firefox that blocked the upload.

**Comment by andreasrosdal** [comment]
Do you get the same problem at https://fcw.movingborders.es/ ?

Can you try in another browser?

Can you try to use a inspector, to see if the Canvas element is there in the page?

**Comment by kvilhaugsvik** [comment]
https://fcw.movingborders.es/  has the same problem. Firefox on Debian on x86 worked fine. So the problem is Brave on Debian on x86. Brave on Windows works according to Lexxie.

**Comment by andreasrosdal** [comment]
Can you please submit a pull request to fix this?

**Comment by kvilhaugsvik** [comment]
Update: Reported to work with Bravee on Arch Linux using the amdgpu drivers. https://github.com/brave/brave-browser/issues/14935#issuecomment-807604894

If this is just me and not all Brave users I can use Firefox or Chromium to test my Freeciv-web changes.

**Comment by Lexxie9952** [comment]
Works with Brave on Windows 10. I suspect it's an issue with Brave not working right on that particular Debian installation, and not a FCW bug.
