### ISSUE TITLE
Game currently broken, Freeciv server segfaults

### ISSUE THREAD

**Issue by andreasrosdal** [Lexxie9952/fcw.org-server#52]
Lexxie reports that the game is currently broken.
Units can't be moved. It crashes.
@cazfi can you take a look?

**Comment by cazfi** [comment]
Haven't seen such a problem, but it sounds like something in the action (such as unit move) targets protocol changes is not working.

**Comment by andreasrosdal** [comment]
Can you please help us test and fix it? Lexxie is very anxious to get it fixed. We can't introduce breaking changes, and most test regularly.

I plan on adding a new testing framework soon.

**Comment by cazfi** [comment]
I would need to be able to reproduce it.

**Comment by andreasrosdal** [comment]
Just start a game. then try to move units. then it crashes, she said. Have you tested the most recent version?

**Comment by cazfi** [comment]
Stupid question, but does she have updated both sides (server and web-client) for the protocol updates?

**Comment by cazfi** [comment]
Just did a complete rebuild from master. Unit moves work with keyboard, goto, autoexplore...

**Comment by andreasrosdal** [comment]
great, then we just need to help her

**Comment by cazfi** [comment]
Also, 'git status' shows that my tree is clean - no local changes forgotten to be committed.

**Comment by cazfi** [comment]
So, what's the commit id she's using (the report came about the same time you merged latest pull request, so I'm not sure if she has that or not)? Does 'git status' show clean tree for her?

**Comment by andreasrosdal** [comment]
it works for her now.

**Comment by andreasrosdal** [comment]
Please keep the pull requests coming.
