### ISSUE TITLE
Freeciv-proxy improvements from lonemadmax/freeciv-web

### ISSUE THREAD

**Issue by andreasrosdal** [Lexxie9952/fcw.org-server#6]
Freeciv-proxy improvements from lonemadmax/freeciv-web

We should probably copy these:
https://github.com/lonemadmax/freeciv-web/commit/34bab9cb8c466be5bb0ac2066548aa34bb5b77d9

https://github.com/lonemadmax/freeciv-web/commits/movingborders

**Comment by Lexxie9952** [comment]
See commit entitled:
"Cherry-pick https://github.com/lonemadmax/freeciv-web/commit/34bab9cb8c466be5bb0ac2066548aa34bb5b77d9"
Hopefully this won't break anything !!!
