### ISSUE TITLE
Template was precompiled with a newer version of Handlebars than the current runtime. Please update your runtime to a newer version (>= 4.3.0).

### ISSUE THREAD

**Issue by andreasrosdal** [Lexxie9952/fcw.org-server#8]
Template was precompiled with a newer version of Handlebars than the current runtime. Please update your runtime to a newer version (>= 4.3.0).

I get this when running the latest version from Git.

**Comment by andreasrosdal** [comment]
![image](https://user-images.githubusercontent.com/41650711/66274862-26279980-e883-11e9-97b4-519f5f345734.png)

**Comment by andreasrosdal** [comment]
Fix is here:  https://github.com/freeciv/freeciv-web/pull/298

**Comment by Lexxie9952** [comment]
See fb42b8f9cd0ec3ebef58a8eb923e296e925e67eb which should fix it
