### ISSUE TITLE
FCW crashes after a while

### ISSUE THREAD

**Issue by andreasrosdal** [Lexxie9952/fcw.org-server#89]
I tried playing a fine game of FCW. After perhaps 30 turns, the game crashed. The game crashes fairly consistently after some minutes of playing.
I have attached the logs. The C server doesn't segfault, I think. 
However, there are errors in the logs, which I will attach. 
I think is could be related to the new orders stuff. Possibly playing the Europe scenario.

This looks relevant:
1: in dio_get_uint8_json_internal() [../../../freeciv/common/networking/dataio_json.c::344]: ERROR: Unable to get uint8 from location: orders
1: in load_ruleset_units() [../../freeciv/server/ruleset.c::1768]: Error loading the default veteran system: "/home/vagrant/freeciv/share/freeciv/mpplus/units.ruleset": Different lengths for the veteran settings in section 'veteran_system'
1: in load_ruleset_units() [../../freeciv/server/ruleset.c::1768]: Error loading the default veteran system: "/home/vagrant/freeciv/share/freeciv/mpplus/units.ruleset": Different lengths for the veteran settings in section 'veteran_system'
1: in load_ruleset_game() [../../freeciv/server/ruleset.c::6357]: "/home/vagrant/freeciv/share/freeciv/mpplus/game.ruleset" [actionenabler_irrigate_tf] lists unknown action type "Irrigate TF".
1: in load_ruleset_game() [../../freeciv/server/ruleset.c::6357]: "/home/vagrant/freeciv/share/freeciv/mpplus/game.ruleset" [actionenabler_irrigate_tf] lists unknown action type "Irrigate TF".
1: in load_ruleset_game() [../../freeciv/server/ruleset.c::6357]: "/home/vagrant/freeciv/share/freeciv/mpplus/game.ruleset" [actionenabler_irrigate_tf] lists unknown action type "Irrigate TF".
1: in load_ruleset_game() [../../freeciv/server/ruleset.c::6357]: "/home/vagrant/freeciv/share/freeciv/mpplus/game.ruleset" [actionenabler_irrigate_tf] lists unknown action type "Irrigate TF".
1: in dio_get_uint8_json_internal() [../../../freeciv/common/networking/dataio_json.c::344]: ERROR: Unable to get uint8 from location: orders
1: in dio_get_uint8_json_internal() [../../../freeciv/common/networking/dataio_json.c::344]: ERROR: Unable to get uint8 from location: orders
1: in load_ruleset_units() [../../freeciv/server/ruleset.c::1768]: Error loading the default veteran system: "/home/vagrant/freeciv/share/freeciv/mpplus/units.ruleset": Different lengths for the veteran settings in section 'veteran_system'

**Comment by andreasrosdal** [comment]
[error-logs.txt](https://github.com/Lexxie9952/fcw.org-server/files/6372737/error-logs.txt)

**Comment by cazfi** [comment]
Seems like @Lexxie9952 has not yet updated mpplus to some ruleset format changes:
- vetaran system errors are probably because lack of rename of "veteran_raise_chance" rename
- "Irrigate TF" should have been updated to "Cultivate"

**Comment by cazfi** [comment]
> 1: in dio_get_uint8_json_internal() [../../../freeciv/common/networking/dataio_json.c::344]: ERROR: Unable to get uint8 from location: orders

This looks weird, though. After the protocol change there should be no uint8 of 'orders' that server tries to read, and checking the server code I see where it would attempt that. It's possible that logging here is faulty, though, and it actually means some member of struct 'orders' instead of uint8 named 'orders'.
What orders are you trying to send? Do you have autosettlers or other automated units sending orders?

**Comment by cazfi** [comment]
You've done full rebuild after the protocol change, have you, so that web-client is in sync with the server code?

**Comment by andreasrosdal** [comment]
> You've done full rebuild after the protocol change, have you, so that web-client is in sync with the server code?

yes

**Comment by andreasrosdal** [comment]
> > 1: in dio_get_uint8_json_internal() [../../../freeciv/common/networking/dataio_json.c::344]: ERROR: Unable to get uint8 from location: orders
> 
> This looks weird, though. After the protocol change there should be no uint8 of 'orders' that server tries to read, and checking the server code I see where it would attempt that. It's possible that logging here is faulty, though, and it actually means some member of struct 'orders' instead of uint8 named 'orders'.
> What orders are you trying to send? Do you have autosettlers or other automated units sending orders?

Lots of goto orders, auto explore, auto settlers.

**Comment by cazfi** [comment]
> It's possible that logging here is faulty, though, and it actually means some member of struct 'orders' instead of uint8 named 'orders'.
Looking the code, that seems to be the case. The logging only cares about the high level structure. The exact field is only logged by log_packet("Corrupt ...") calls in dio_get_unit_order_json(). Can you somehow get the exact field from there? (turning those log_packet() calls to a level you actually see in your logs or something like that)
